# Sample .travis.yml for R projects.
# Taken from my fork of Craig Citro's r-travis
#
# See https://github.com/eddelbuettel/r-travis/
# and https://github.com/craigcitro/r-travis
#
# See README.md for instructions.

language: c

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --as-cran"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_aptget libgsl0-dev
  - ./travis-tool.sh install_r RcppGSL rbenchmark microbenchmark highlight

script: 
  - ./travis-tool.sh run_tests

notifications:
  email:
    on_success: change
    on_failure: change


